CREATE TABLE IF NOT EXISTS shipping_rates (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    courier_id INT UNSIGNED NOT NULL,
    origin VARCHAR(100) NOT NULL,
    destination VARCHAR(100) NOT NULL,
    service_type VARCHAR(50) NOT NULL,
    price_per_kg DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (courier_id) REFERENCES couriers(id) ON DELETE CASCADE
) ENGINE=InnoDB;